### PR TITLE
chore(release): publish packages

### PR DESCRIPTION
**Pull request by smkhalsa**
- ferry@0.10.5-dev.3
 - ferry_exec@0.1.5-dev.2
 - ferry_flutter@0.5.5-dev.3
 - ferry_generator@0.5.0-dev.10
 - ferry_test_graphql@0.1.5-dev.3
 - normalize@0.6.0+1
 - ferry_cache@0.5.5-dev.10

### CODE REVIEW

**Comment by aaahrens** [comment]
ah @smkhalsa just in case you hadn't seen, alpha release is failing with stale creds it looks like.

**Comment by smkhalsa** [comment]
Yes, I saw. I tried to manually publish, but pub.dev won't accept the updated versions with the missing analyzer dependency.

**Comment by aaahrens** [comment]
well that sucks. Want me to PR a`analyzer: ">=1.7.0 <4.0.0"` entry then?

**Comment by smkhalsa** [comment]
I'm already on it. I'm going to do analyzer `'>=2.3.0 <4.0.0'` since that's what `gql_code_builder` uses

**Comment by aaahrens** [comment]
+1

**Comment by smkhalsa** [comment]
Done, new versions published

**Pull request merged**
