### PR TITLE
ferry_flutter: Add error builder to Operation widget

### PR DESCRIPTION
**Pull request by janosroden**
Let developers to handle errors.

### CODE REVIEW

**Comment by smkhalsa** [comment]
@janosroden thanks for your interest in contributing.

Error handling may be handled differently by each application. Simply displaying the errors to users is not always a good idea. Furthermore, developers may want to display errors in different ways (e.g. a dialog). Ferry shouldn't be opinionated about if or how errors are displayed.

If you want to achieve what you've implemented in your PR, you can do so easily by writing a wrapper widget around the existing Operation widget.

**Comment by janosroden** [comment]
@smkhalsa The existing Operation widget doesn't allow to handle stream errors (like in #114).

This pr provides a default builder which can be overwritten in application level and also provides error builder which can be specified for the particular Operation.

So I agree, ferry doesn't have to define how to handle errors but this pr just provides a way to handle errors with a default solution.

If you still think this is overkill then we still can choose to don't call the default handler. That would be a backward compatible change. What do you think?

**Comment by smkhalsa** [comment]
> @smkhalsa The existing Operation widget doesn't allow to handle stream errors (like in #114).

This is a fair point, although I'm not convinced that internal TypedLink errors should be handled at the Widget level.

Ferry already has an `ErrorTypedLink`, although it's not included in the default client TypedLink chain. It's currently untested, but we could look at adding it.

Anything related to displaying errors, however, can be handled as a simple wrapper around the existing widget

**Comment by janosroden** [comment]
If I understand correctly `ErrorTypedLink` can help to catch errors before the stream is created but 'runtime' errors are not its responsibility. However it seems useful, thanks for the hint.

The motivation of this PR was that when I tried the library I found the Operation widget, started using and I got null `response` in the builder (due to an unhandled custom scalar). Then I looked into the code how to access to the original `snapshot.error`. I had to copy because `snapshot.error` is simply ignored. Even the stream is created by the widget so no way to pass a stream which is already prepared with onError.

I'd be happy with the 'simple wrapper' you mentioned but I think it would be useful to access to all errors. Otherwise the builders will look like `if (response == null) return Text('Something went wrong');` :)
I can imagine a link which converts stream errors to `OperationResponse` with link exception.

At least do you agree to don't hide the stream error?

**Comment by smkhalsa** [comment]
Error handling has been admittedly lacking until now. We've discussed in the past how to handle Stream error events (i.e. whether to catch them or let the user catch them), and we decided to let the user catch them.

However, as you mentioned, this has led to some unexpected behavior caused by silently failing TypedLinks. With our TypedLink architecture, it makes sense to add some reasonable error handling defaults to the default Client TypedLink.

I've updated the `ErrorTypedLink` to catch Stream error events and convert them into `OperationResponse`s and have included `ErrorTypedLink` in the default `Client` TypedLink chain.

I've also adjusted `ferry_flutter` to include errors from the StreamBuilder (although there shouldn't be any in the default `Client` due to the above). This is a breaking change since it changes the signature of the builder callback.

Please take a look at the [PR](https://github.com/gql-dart/ferry/pull/151) and let me know if it resolves all issues in your use case.

**Pull request closed without merging**
