### PR TITLE
Update Analyzer Dependency

### LINKED ISSUE #361: Allow `ferry_generator` to use `analyzer >= 4.0.0`
I'm having issues when I'm trying to use other libraries along with `ferry_generator` (for example, `drift_dev`):

```
Because no versions of ferry_generator match >0.5.0-dev.10 <0.6.0 and ferry_generator 0.5.0-dev.10 depends on analyzer >=2.3.0 <4.0.0, ferry_generator ^0.5.0-dev.10 requires analyzer >=2.3.0 <4.0.0.
And because drift_dev 1.7.0 depends on analyzer ^4.0.0 and no versions of drift_dev match >1.7.0 <2.0.0, ferry_generator ^0.5.0-dev.10 is incompatible with drift_dev ^1.7.0.
So, because my_app depends on both drift_dev ^1.7.0 and ferry_generator ^0.5.0-dev.10, version solving failed.
```

Is it possible to upgrade the `analyzer` dependency?

### PR DESCRIPTION
**Pull request by 2shrestha22**
closes #361

### CODE REVIEW

**Comment by 2shrestha22** [comment]
This PR needs to be published to pass these checks. https://github.com/gql-dart/gql/pull/328

**Comment by knaeckeKami** [comment]
I think you need to run code generation on the test packages and include the generated code in your PR.
packages like ferry_test_codegen intentionally contain generated code so we see if the generated code changes.

**Comment by knaeckeKami** [comment]
please revert [fd98ba9](https://github.com/gql-dart/ferry/pull/363/commits/fd98ba9130d3b61aec9be788d2569f1877ef2ee7) again. 

The code gen is omitted on purpose to make sure that the generated code checked in the repository actually matches the real generated code.

**Comment by knaeckeKami** [comment]
Nice! let me test this locally on my real app as smoke test.

**Comment by knaeckeKami** [comment]
LGTM

**Pull request merged**
