### PR TITLE
Fix bug with fragments on same object with different fields

### LINKED ISSUE #39: Denormalization does not merge data of expanded fragments
There is an issue with the `denormalizeNode` function in the `normalize` package.

It denormalizes all fragments in a query one by one. The values of the fields requested by a fragment are then stored in a `result` map under the key of the queried field. If the same field is queried again by another fragment, the value stored before is replaced.

This is problematic if multiple fragments query an object, but query different fields of that object. In that case only the object data of the last processed fragment is present in the result.

Here is an example. Consider the following query and fragments.

```graphql
fragment MovieStarComponent on MovieType {
	__typename
	id
	name
	starRole {
		__typename
		id
		name
		age
		haircolor
	}
}

fragment MovieTitleComponent on MovieType {
	__typename
	id
	name
	starRole {
		__typename
		id
		name
	}
}

query MovieByID($movieID: ID!) {
	movie(id: $movieID) {
		... MovieStarComponent
		... MovieTitleComponent
	}
}
```

Running `denormalize` on this query will result in the following map:

```
{
	movie {
		__typename: MovieType,
		id: 1,
		name: Rocky,
		starRole {
			__typename: ActorType,
			id: 1,
			name: Sylvester Stallone,
		}

	}
}
```

Notice that the `starRole` objects `age` and `haircolor` fields are not returned, even though they are queried by the `MovieStarComponent` fragment.

Here the `MovieStarComponent` fragment is processed first. The `result` map now contains the queried movies `starRole` object and all fields queried by the `MovieStarComponent` fragment.

Next the `MovieTitleComponent` fragment is processed. It queries the same  `starRole` object but less fields than the `MovieStarComponent` fragment.

Due to the bug described before, the data queried by the `MovieStarComponent` fragment is replaced with the data of the `MovieTitleComponent` fragment.

Changing the order of the fragments in this particular query would "fix" the issue in this situation.

#### Solution

One solution to fix this problem would be to deepmerge the data of denormalized fragments on the same level, instead of just keeping the data of the last processed fragment. I will create an PR in a minute with such changes.

### PR DESCRIPTION
**Pull request by smkhalsa**
fixes #39. An alternative to #40.

### CODE REVIEW

**Comment by iscriptology** [comment]
Publish ETA?

**Comment by smkhalsa** [comment]
It's already published

**Comment by smkhalsa** [comment]
https://pub.dev/packages/normalize

**Comment by DoctorJohn** [comment]
ferry and ferry_cache list normalize ^0.1.1 in their dependencies. Shouldn't we update those?

**Comment by iscriptology** [comment]
I meant under ferry

**Comment by smkhalsa** [comment]
Done. New versions published for `ferry` and `ferry_client`.

**Pull request merged**
