### PR TITLE
Fixed issue with update cache typed link

### PR DESCRIPTION
**Pull request by lotus-x**
When using a link that emits sequential responses for a single request (like graphql subscription) it only invoke the cache handler for the first response only. So this is a fix for the issue.

`runNonOptimistically` should be true default for the common requests. For a request with `DataSource.Link` it should be marked as `false` then again it should be `true` after update the cache.

### CODE REVIEW

**Comment by dev-pos** [comment]
this should fix #212, right? @lotus-x

**Comment by smkhalsa** [comment]
Thanks for the PR.

As you can see from the failed tests, simply changing the default for `runNonOptimistically` to `true` isn't a valid solution.

Also, it would be great if you could add a new test to the tests folder for the issue you are describing.

**Comment by lotus-x** [comment]
Thanks for reviewing this and I'm sorry to make some quick changes. I will go through the tests and give a reliable solution asap.

Anyway why don't anyone get this issue yet? no one using subscriptions? Am I taking some misleading path?

**Comment by smkhalsa** [comment]
Sounds good. I can't say if anyone else has experienced this yet, but I don't use subscriptions in my project

**Comment by smkhalsa** [comment]
Closing due to inactivity, but please reopen if you're still working on this.

**Pull request closed without merging**
