### PR TITLE
feat: allow importing schema from other package

### PR DESCRIPTION
**Pull request by knaeckeKami**
experiment for supporting monorepos

### CODE REVIEW

**Comment by meg4cyberc4t** [comment]
Don't give it up! A very important feature!

**Comment by MattisBrizard** [comment]
Hi @knaeckeKami, I think this would be a top feature for monorepos 
Do you think that there is still much to do to ship this feature ?

**Comment by knaeckeKami** [comment]
IMO it won't take much more to ship this, but I kinda abandoned it since there is an issue:

The current architecture uses built_value, it generates a `Serializers` object which knows how to serialize each generated built_value type.

ferry currently assumes that this serializers type can serialize all types - at least for offline mutations that's required.

But in a monorepo, every repo would generate its own `Serializers` instance, which only knows how to serialize the types form this repo.

I don't have a good solution for this right now.

**Comment by MattisBrizard** [comment]
It's not possible to have each package generating their own `Serializers` and merge it with the as you mentioned here :
> * feature packages depend on the schema file and import the generated .schema.gql.dart file instead of generating their own. They also generate their own `Serializers` class and merge it with the `Serializers` ([pub.dev/documentation/built_value/latest/serializer/Serializers/merge.html](https://pub.dev/documentation/built_value/latest/serializer/Serializers/merge.html) ) from the schema in order so ensure that they can fully serialize all required types.

**Comment by MattisBrizard** [comment]
It's not possible to have each package generate its own Serializers and merge it with the one from the schema?
As you mentioned [here](https://github.com/gql-dart/ferry/issues/531#issuecomment-1681980509):

> * feature packages depend on the schema file and import the generated .schema.gql.dart file instead of generating their own. They also generate their own `Serializers` class and merge it with the `Serializers` ([pub.dev/documentation/built_value/latest/serializer/Serializers/merge.html](https://pub.dev/documentation/built_value/latest/serializer/Serializers/merge.html) ) from the schema in order so ensure that they can fully serialize all required types.

**Comment by knaeckeKami** [comment]
That might be possible, but that would introduce cyclic dependencies; the final `Serializers ` would need to depend on every  repository in the monorepo.
And then, what's the point of having a monorepo?

**Comment by knaeckeKami** [comment]
fixed by #606

**Pull request closed without merging**
