### PR TITLE
chore: Upgrade rxdart

### PR DESCRIPTION
**Pull request by mcmah309**

### CODE REVIEW

**Comment by knaeckeKami** [comment]
Thanks!

It seems that there are behavioral changes in rxdart which break some features of ferry related to paging + watching the cache.

**Comment by mcmah309** [comment]
Given my current knowledge gap of the repo, I don't think I'll have the bandwidth to dive in and resolve this. I was hoping this would be a simple update. Will you be able support this upgrade initiative?

**Comment by knaeckeKami** [comment]
yes, you can try #612

The tests seems to work, but there is an additional run in the event loop required now due to the change in rxdart, which might affect widget tests (see the changed tests in the PR)

**Comment by mcmah309** [comment]
Closing as https://github.com/gql-dart/ferry/pull/612 was merged

**Pull request closed without merging**
