### PR TITLE
feat(vars-builder-generator): Adding `vars_create_factories` to ferry_generator|graphql_builder

### PR DESCRIPTION
**Pull request by caffeineflo**
Hello/Hallo/Servus/Grüß Gott @knaeckeKami,

Now that https://github.com/gql-dart/gql/pull/434 is merged, I thought I'll hold true to my word and open this PR to hover up the newly introduced `vars_create_factories` option to Ferry!

This PR relies on a new version release of the `gql` package though, that still needs to be released and assumes it's going to be version 0.9.2 - let me know if you you prefer a different way of doing this.

While writing the docs for this new version, I also noticed that the new `tristate_optionals` option was missing in the docs, so I took the liberty to add that as well - hope you don't mind! 

Let me know if anything else needs to be changed! 

Thanks!

### CODE REVIEW

**Comment by knaeckeKami** [comment]
Hi and Servus ;)!

Thanks for the PR, I'll release a new version of the code builder so that the PR can succeed. 

And thanks for the additional documentation.

ferry relies on conventional commits to automatically generate changelogs, so please add `feat(ferry_generator):` to the title of the PR on github and as prefix your your commit messages.

**Comment by knaeckeKami** [comment]
also, please update your PR from the master branch, analyze fails because of a new lint

**Comment by knaeckeKami** [comment]
Ah, I see that gql_code_builder actually has breaking changes, since a new required parameter was added. so i published it at 0.10.0, not 0.9.2.

**Comment by caffeineflo** [comment]
I think I have all things fixed now, so should be good to go if the CI gods decide to approve of these changes as well! Thanks

**Pull request merged**
